application: djangae-template-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/(mapreduce|queue|warmup).*
  script: wsgi.application
  login: admin

- url: /media
  static_dir: templates/static_files

- url: /.*
  script: wsgi.application

skip_files:
  - manage.py